name: Build, Tag, and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU for ARM64 builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      - name: Build Docker Image
        id: build
        run: |
          docker buildx build --platform linux/arm64 \
            --file Dockerfile \
            --tag registry.digitalocean.com/k8s1/doctl_kubectl:build \
            --output type=docker \
            .

      - name: Tag Docker Image
        id: tag
        run: |
          docker tag registry.digitalocean.com/k8s1/doctl_kubectl:build registry.digitalocean.com/k8s1/doctl_kubectl:latest

      - name: Push Docker Image
        run: |
          docker push registry.digitalocean.com/k8s1/doctl_kubectl:build
          docker push registry.digitalocean.com/k8s1/doctl_kubectl:latest

