name: Build and Push Docker Image to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 2: Log in to the DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      # Step 3: Build and push the Docker image for ARM64 platform
      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/arm64 \
            -t registry.digitalocean.com/k8s1/doctl_kubectl:latest \
            --push \

