name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Log in to the DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: |
          echo "${{ secrets.DO_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      # Step 2: Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/arm64 \
            -t registry.digitalocean.com/k8s1/doctl_kubectl:latest \
            --push \
            .

