name: Build and Push Docker Image

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  build-and-push:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      - name: Build and Push Docker Image for ARM64
        run: |
          docker buildx build --platform linux/arm64 \
            -t registry.digitalocean.com/k8s1/doctl_kubectl:${{ github.sha }} \
            -t registry.digitalocean.com/k8s1/doctl_kubectl:latest \
            --push .

      - name: Log out of Docker
        run: docker logout registry.digitalocean.com

