name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up QEMU for ARM64 builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to the DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: |
          echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      # Step 5: Build the Docker image
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/arm64 \
            --file Dockerfile \
            --tag registry.digitalocean.com/k8s1/doctl_kubectl:build \
            --output type=docker .
          
      # Step 6: Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag registry.digitalocean.com/k8s1/doctl_kubectl:build registry.digitalocean.com/k8s1/doctl_kubectl:latest

      # Step 7: Push the Docker image
      - name: Push Docker Image
        run: |
          docker push registry.digitalocean.com/k8s1/doctl_kubectl:latest

