name: Create DigitalOcean Kubernetes Cluster

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create-cluster:
    name: "Create Kubernetes Cluster"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run commands in Docker container
        run: |
          docker run --rm \
            -e DO_API_TOKEN=${{ secrets.DO_API_TOKEN }} \
            registry.digitalocean.com/k8s1/doctl_kubectl /bin/sh -c "
              # Initialize doctl with the access token
              doctl auth init --access-token $DO_API_TOKEN &&
              # Create Kubernetes cluster
              doctl kubernetes cluster create my-cluster --region nyc1
            "

