name: Create DigitalOcean Kubernetes Cluster

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create-cluster:
    name: "Create Kubernetes Cluster"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      # Get the latest Docker image tag
      - name: Get Docker image tag
        id: get-tag
        run: |
          TAG=$(curl -s https://registry.digitalocean.com/v2/k8s1/doctl_kubectl/tags/list | jq -r '.tags[]' | sort -V | tail -n 1)
          echo "TAG=${TAG}" >> $GITHUB_ENV

      # Verify Docker image tag
      - name: Verify Docker image tag
        run: echo "Docker image tag: ${{ env.TAG }}"  # Debug output

      # Run Docker container to create Kubernetes cluster
      - name: Run commands in Docker container
        run: |
          if [ -z "${{ env.TAG }}" ]; then
            echo "Error: Docker image tag is not set"
            exit 1
          fi

          docker run --rm \
            -e DO_API_TOKEN=${{ secrets.DO_API_TOKEN }} \
            registry.digitalocean.com/k8s1/doctl_kubectl:${{ env.TAG }} /bin/sh -c "
              # Initialize doctl with the access token
              doctl auth init --access-token \$DO_API_TOKEN &&
              # Create Kubernetes cluster
              doctl kubernetes cluster create my-cluster --region nyc1
            "

      # Log out from DigitalOcean Container Registry
      - name: Log out of Docker
        run: docker logout registry.digitalocean.com

