---
name: Run doctl
on:
  push:
    branches:
      - main
jobs:
  doctl:

    runs-on: ubuntu-latest  # The GitHub Actions runner environment

    steps:
      # Step 1: Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      # Step 2: Run the job inside the Docker image from the DigitalOcean Container Registry
      - name: Run commands in the container
        container:
          image: registry.digitalocean.com/k8s1/doctl_kubectl:latest

        # Step 3: Run commands inside the container
        
        run: |
          # Run doctl to save the kubeconfig
          doctl kubernetes cluster kubeconfig save example-k8s-cluster  # Replace with your actual cluster name
          
          # Run kubectl to interact with the Kubernetes cluster
          kubectl get nodes

