name: Run doctl

on:
  push:
    branches:
      - main

jobs:
  doctl:
    container:
      image: registry.digitalocean.com/k8s1/doctl_kubectl:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run doctl        
        run: |
          doctl kubernetes cluster kubeconfig save example-k8s-cluster  # Replace with your actual cluster name

      - name: Run kubectl        
        run: |
          kubectl get nodes

