name: "Deploy to Kubernetes on YAML Change"

on:
  push:
    paths:
      - 'deployments/**/*.yaml'  # Adjust this path as needed

env:
  KUBECONFIG_PATH: "/tmp/kubeconfig"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with DigitalOcean
        run: |
          doctl auth init --access-token ${{ secrets.DO_API_TOKEN }}

      - name: Download Kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save <your-cluster-name> --kubeconfig=$KUBECONFIG_PATH

      - name: Apply Kubernetes Manifests
        run: |
          export KUBECONFIG=$KUBECONFIG_PATH
          kubectl apply -f deployments/

