name: Deploy to Kubernetes

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  deploy:
    name: "Deploy to Kubernetes Cluster"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      - name: Pull Docker Image
        run: docker pull registry.digitalocean.com/k8s1/doctl_kubectl:latest

      - name: Download kubeconfig using doctl
        run: |
          docker run --rm \
            -e DO_API_TOKEN="${{ secrets.DO_API_TOKEN }}" \
            registry.digitalocean.com/k8s1/doctl_kubectl:latest \
            doctl kubernetes cluster kubeconfig save ${CLUSTER_NAME}
        env:
          CLUSTER_NAME: "example-k8s-cluster"  # Replace with your cluster name

      - name: Apply Kubernetes Resources
        run: |
          docker run --rm \
            -v $HOME/.kube/config:/root/.kube/config \
            -v $GITHUB_WORKSPACE/deployments:/deployments \
            registry.digitalocean.com/k8s1/doctl_kubectl:latest \
            kubectl apply -f /deployments
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Clean up
        run: docker logout registry.digitalocean.com

