name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: registry.digitalocean.com/k8s1/doctl_kubectl:latest
      credentials:
        password: ${{ secrets.DO_API_TOKEN }}

    steps:
      - name: Authenticate with DigitalOcean API
        run: doctl auth init -t ${{ secrets.DO_API_TOKEN }}

      - name: Retrieve kubeconfig and apply manifests
        run: |
          # Retrieve kubeconfig from your Kubernetes cluster
          doctl kubernetes cluster kubeconfig save example-k8s-cluster  # Replace with your actual cluster name
          
          # Apply the Kubernetes manifests
          kubectl apply -f deployments/

