name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Docker Container for Kubernetes Deployment
        run: |
          docker run --rm \
            --platform linux/amd64 \
            -e DO_API_TOKEN=${{ secrets.DO_API_TOKEN }} \
            -v $(pwd)/deployments:/deployments \
            -v $(pwd)/.kube:/root/.kube \
            registry.digitalocean.com/k8s1/doctl_kubectl:latest /bin/sh -c "
              # Authenticate with DigitalOcean API
              doctl auth init -t \$DO_API_TOKEN && \
              # Retrieve kubeconfig from your Kubernetes cluster and save it to a known location
              doctl kubernetes cluster kubeconfig save example-k8s-cluster -o /root/.kube/config && \
              # Copy kubeconfig to the repo
              cp /root/.kube/config /workspace/.kube/config && \
              # Print the kubeconfig for debugging
              echo 'kubeconfig:' && cat /workspace/.kube/config && \
              # Use the kubeconfig for kubectl commands
              kubectl get nodes --kubeconfig /workspace/.kube/config && \
              # Apply the Kubernetes manifests
              kubectl apply -f /deployments/ --kubeconfig /workspace/.kube/config && \
              # Verify the deployment status
              kubectl get pods --kubeconfig /workspace/.kube/config && \
              kubectl get deployments --kubeconfig /workspace/.kube/config && \
              kubectl rollout status deployment/your-deployment-name --kubeconfig /workspace/.kube/config
            "

