name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      # Step 2: Use the Docker image from DigitalOcean Container Registry
      - name: Run commands inside the Docker image
        uses: docker://registry.digitalocean.com/k8s1/doctl_kubectl:latest
        with:
          entrypoint: ["/bin/sh", "-c"]
        run: |
          # Authenticate with DigitalOcean API
          doctl auth init -t ${{ secrets.DO_API_TOKEN }}
          
          # Retrieve kubeconfig from your Kubernetes cluster
          doctl kubernetes cluster kubeconfig save example-k8s-cluster  # Replace with your actual cluster name
          
          # Apply the Kubernetes manifests
          kubectl apply -f deployments/

