name: Run doctl and kubectl

on:
  push:
    branches:
      - main  # Triggers the workflow when a push is made to the 'main' branch

jobs:
  bash_command_job:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner with Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install doctl (DigitalOcean CLI)
        run: |
          curl -LO https://github.com/digitalocean/doctl/releases/download/v1.114.0/doctl-1.114.0-linux-amd64.tar.gz && \
          tar -xzf doctl-1.114.0-linux-amd64.tar.gz && \
          chmod +x doctl && \
          sudo mv doctl /usr/local/bin/

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
          chmod +x kubectl && \
          sudo mv kubectl /usr/local/bin/

      - name: Run doctl to fetch kubeconfig
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}  # Using GitHub Secrets for API token
        run: |
          doctl auth init --access-token "${{ secrets.DO_API_TOKEN }}"
          doctl kubernetes cluster kubeconfig save example-k8s-cluster  # Replace with your actual cluster name

      - name: Run kubectl to get nodes
        run: |
          kubectl --kubeconfig="$HOME/.kube/config" get nodes

