name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: registry.digitalocean.com/k8s1/doctl_kubectl:latest

    steps:
      # Step 1: Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      # Debug: Check Docker login
      - name: Debug Docker Login
        run: docker info

      # Debug: Verify available Docker images
      - name: List Docker Images
        run: docker images

      # Debug: Verify available Docker networks
      - name: List Docker Networks
        run: docker network ls

      # Step 2: Run commands inside the container
      - name: Authenticate with DigitalOcean and apply Kubernetes manifests
        run: |
          # Authenticate with DigitalOcean API
          doctl auth init -t ${{ secrets.DO_API_TOKEN }}
          # Retrieve kubeconfig from your Kubernetes cluster
          doctl kubernetes cluster kubeconfig save example-k8s-cluster  # Replace with your actual cluster name
          # Apply the Kubernetes manifests
          kubectl apply -f deployments/

