name: Run doctl

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    outputs:
      login-success: ${{ steps.login.outputs.success }}
    steps:
      - name: Log in to DigitalOcean Container Registry
        id: login
        run: |
          echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin
          echo "success=true" >> $GITHUB_ENV

  deploy:
    needs: login
    runs-on: ubuntu-latest
    container:
      image: registry.digitalocean.com/k8s1/doctl_kubectl:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run commands inside the container
        run: |
          # Run doctl to save the kubeconfig
          doctl kubernetes cluster kubeconfig save example-k8s-cluster  # Replace with your actual cluster name
          
          # Run kubectl to interact with the Kubernetes cluster
          kubectl get nodes

