name: Run doctl

on:
  push:
    branches:
      - main

jobs:
  doctl:
    # Use the container image for the entire job
    container:
      image: registry.digitalocean.com/k8s1/doctl_kubectl:latest

    runs-on: ubuntu-latest  # Runner environment

    steps:
      # Step 1: Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      # Step 2: Run commands inside the container
      - name: Run commands
        run: |
          # Run doctl to save the kubeconfig
          doctl kubernetes cluster kubeconfig save example-k8s-cluster  # Replace with your actual cluster name
          
          # Run kubectl to interact with the Kubernetes cluster
          kubectl get nodes

