name: Docker and Kubernetes Setup

on:
  workflow_dispatch:
    inputs:
      cluster_id:
        description: 'The ID of the Kubernetes cluster'
        required: true
        type: string

env:
  DOCKER_IMAGE: "registry.digitalocean.com/k8s1/doctl_kubectl"
  KUBECONFIG_PATH: "/tmp/kubeconfig"  # Path where kubeconfig will be saved

jobs:
  setup-and-run:
    name: "Configure Kubernetes and Run Commands"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run commands in Docker container
        run: |
          docker run --rm \
            -e DO_API_TOKEN=${{ secrets.DO_API_TOKEN }} \
            -e KUBECONFIG_PATH=/tmp/kubeconfig \
            registry.digitalocean.com/k8s1/doctl_kubectl:latest /bin/sh -c "
              doctl auth init --access-token $DO_API_TOKEN &&
              doctl kubernetes cluster kubeconfig save ${{ github.event.inputs.cluster_id }} --kubeconfig $KUBECONFIG_PATH &&
              kubectl --kubeconfig $KUBECONFIG_PATH get nodes
            "

