name: Docker and Kubernetes Setup

on:
  workflow_dispatch:
    inputs:
      kubeconfig_path:
        description: 'The path where the kubeconfig will be saved'
        required: true
        type: string

env:
  DOCKER_IMAGE: "registry.digitalocean.com/k8s1/doctl_kubectl"
  KUBECONFIG_PATH: "/tmp/kubeconfig"  # Path where kubeconfig will be saved

jobs:
  setup-and-run:
    name: "Configure Kubernetes and Run Commands"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run commands in Docker container
        run: |
          docker run --rm \
            -e DO_API_TOKEN=${{ secrets.DO_API_TOKEN }} \
            -e KUBECONFIG_PATH=/tmp/kubeconfig \
            ${{ env.DOCKER_IMAGE }} /bin/sh -c "
              # Initialize doctl with the access token
              doctl auth init --access-token $DO_API_TOKEN &&
              # Note: Replace or remove the following line if not applicable
              echo 'No Kubernetes cluster ID provided, skipping kubeconfig save.' &&
              # Run kubectl command or other operations
              kubectl --kubeconfig $KUBECONFIG_PATH get nodes || echo 'No nodes available or kubeconfig not set up'
            "

