name: Docker and Kubernetes Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: "registry.digitalocean.com/k8s1/doctl_kubectl"
  KUBECONFIG_PATH: "/kube/config/path"  # Adjust this path as needed
  DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}

jobs:
  build-and-push:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Log out of Docker
        run: docker logout registry.digitalocean.com

  kube-config:
    name: "Configure Kubernetes and Run Commands"
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run doctl and kubectl commands
        uses: docker://registry.digitalocean.com/k8s1/doctl_kubectl:${{ github.sha }}
        with:
          entrypoint: /bin/sh
          args: -c "doctl kubernetes cluster kubeconfig save <cluster-id> && kubectl get nodes"

