name: Docker and Kubernetes Setup

on:
  workflow_dispatch:
    inputs:
      cluster_id:
        description: 'The ID of the Kubernetes cluster'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t doctl_kubectl:latest .

      - name: Run Docker Container and Configure Kube
        uses: docker://doctl_kubectl:latest
        with:
          args: |
            sh -c "
              doctl auth init --access-token ${{ secrets.DO_API_TOKEN }} &&
              doctl kubernetes cluster kubeconfig save ${{ github.event.inputs.cluster_id }} --kubeconfig /root/.kube/config &&
              kubectl --kubeconfig /root/.kube/config get nodes
            "

