name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'

env:
  TF_CLOUD_ORGANIZATION: "infra-test-90"
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: "learn-terraform-github-action"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform-apply:
    name: "Apply Terraform Configuration"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

